channels:
  - conda-forge

dependencies:
  - python=3.9.13               # https://pyreadiness.org/3.9/         
  - poppler=22.04.0             # https://anaconda.org/conda-forge/poppler
  - pdf2image=1.16.0            # https://anaconda.org/conda-forge/pdf2image
